require("walter.plugins-setup")
require("walter.core.options")
require("walter.core.keymaps")
require("walter.core.colorscheme")

require("walter.plugins.comment")
require("walter.plugins.nvim-tree")
require("walter.plugins.nvim-web-devicons")
require("walter.plugins.lualine")
require("walter.plugins.telescope")
require("walter.plugins.nvim-cmp")

require("walter.plugins.lsp.mason")
require("walter.plugins.lsp.lspsaga")
require("walter.plugins.lsp.lspconfig")
